### ISSUE TITLE
Browser version of Safari User Agents

### ISSUE THREAD

**Issue by mario-zelger** [mycsharp/HttpUserAgentParser#34]
Consider the following Safari User Agent strings:
*Standard*
`Mozilla/5.0 (Macintosh; Intel Mac OS X 13_0_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15`

*iPhone*
`Mozilla/5.0 (iPhone; CPU iPhone OS 16_1_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Mobile/15E148 Safari/604.1`

The current implementation returns `605.1.15` (or `604.1`) as the version of the User Agent. I would argue that in the case of Safari the version `16.1` would be the correct value (in both cases). For example the *MDN Web Docs* and *[Can I Use](https://caniuse.com/)* work with this versioning.

I guess this would require to change [this line](https://github.com/mycsharp/HttpUserAgentParser/blob/main/src/MyCSharp.HttpUserAgentParser/HttpUserAgentStatics.cs#L109) from `CreateDefaultBrowserRegex("Safari"), "Safari" }` to `CreateDefaultBrowserRegex("Version"), "Safari" }`. 

What do you think?

**Comment by BenjaminAbt** [comment]
Thanks for pointing out the (new?) version behavior.

I'll have a look at it the days and what effects it has (also for consumers of the lib).

**Comment by BenjaminAbt** [comment]
As note https://regex101.com/r/gRLirS/1 cc @gfoidl

**Comment by BenjaminAbt** [comment]
Small update: I've been looking into this and I'm still looking for a way to efficiently evaluate both options.

**Comment by mario-zelger** [comment]
Thanks for the update and for your work!

**Comment by Santas** [comment]
Looking at AppleWebKit version is not very useful, because this part of user agent is frozen from Safari ±11.1 and all newer desktop versions report the same "605.1.15" version.

**Comment by BenjaminAbt** [comment]
Yes, this is the case for privacy reasons.

I've been researching this issue on and off, and haven't come to a conclusion on what the best way is.
Therefore I have not posted a status.

**Comment by Santas** [comment]
What problems do you see with reporting "Version" part of UA as Version other than this being possibly a breaking change? The Version string seems to be consistently reported from Safari 3.
