### ISSUE TITLE
WhatsApp user agent

### ISSUE THREAD

**Issue by brunobritodev** [mycsharp/HttpUserAgentParser#46]
hi guys, congratulations for the great work!

In our application, we need to identify when content is being shared on WhatsApp. I noticed that you have a bot identifier for Facebook (https://github.com/mycsharp/HttpUserAgentParser/blob/94a2aa9a3360f2c26ff707246cc3fd14adc8311e/src/MyCSharp.HttpUserAgentParser/HttpUserAgentStatics.cs#L246), but no one for whatsapp.

Would it make sense to add a check for WhatsApp and classify it as a bot?

More information about WhatsApp's user agent: https://developers.facebook.com/docs/whatsapp/link-previews/

**Comment by BenjaminAbt** [comment]
Mh... “facebookexternalhit” is - as I understand it - the website that loads a link preview as a separate instance.
In the case of WhatsApp, however, this is not a separate instance, but the built-in browser in WhatsApp for a preview, right?

WhatsApp would definitely make sense as an additional entry. But I'm not sure whether it's a browser or a bot.

**Comment by BenjaminAbt** [comment]
The user agent is not 100% accurate anyway. There are enough other examples that have exactly the same case.

We have actually seen “bots” as independent applications, for example crawlers. And at least that's how I understood the Facebook stuff (so far).

Somehow I don't see browser and bot fitting here.  Maybe another type here?
@gfoidl do you have an opinion on this?
With curl, we also have our own type for tools (one entry). Should we perhaps create a new type here or just define WhatsApp as crawler here and add it as bot?

**Comment by gfoidl** [comment]
> just define WhatsApp as crawler here and add it as bot?

That's what I'd do.

**Comment by BenjaminAbt** [comment]
suggestion:
- Add `WhatsApp` as robot

result:
- identified as bot

but:
- no version check (we dont have this for bots today)
- no platform check (we dont have this for bots today)

https://github.com/mycsharp/HttpUserAgentParser/blob/94a2aa9a3360f2c26ff707246cc3fd14adc8311e/src/MyCSharp.HttpUserAgentParser/HttpUserAgentParser.cs#L22
